### ISSUE TITLE
templatizedViewer should take an alias 

### ISSUE THREAD

**Issue by lolopinto** [lolopinto/ent#932]
if the local `Viewer` is called Viewer

```yml
  templatizedViewer:
    path: src/lib/viewer/Viewer.ts
    name: Viewer
```

will give an error because of conflict with ent. should have always have an alias for these things

```
Error: error: Duplicate binding
  
   |
12 | import { Viewer } from '../../../lib/viewer/Viewer';
   |          ^^^^^^
   |
note: Viewer was declared at here
  
   |
4  | import { Data, Ent, Viewer } from '@snowtop/ent';
   |                     ^^^^^^

```
